name: build versioned docs

on:
  release:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r companion.txt
        pip install .
    - uses: docker://pandoc/core
    - name: Build the docs
      run: |
        ./.github/scripts/builddocs.sh versioned
        # rebuild the latest docs to include links to the new version
        ./.github/scripts/builddocs.sh latest
      shell: bash
